### ISSUE TITLE
EqualStreetNames accross the World

### ISSUE THREAD

**Issue by jbelien** [openknowledgebe/equalstreetnames#20]
| Country | City | Link | Data Repository | Maintainer |
|-|-|-|-|-|
| 🇧🇪 | Brugge | - | [equalstreetnames-brugge](https://github.com/openknowledgebe/equalstreetnames-brugge) | @jbelien |
| 🇧🇪 | Brussels | https://equalstreetnames.brussels/ | [equalstreetnames-brussels](https://github.com/openknowledgebe/equalstreetnames-brussels) | @jbelien |
| 🇧🇪 | Gent | - | [equalstreetnames-gent](https://github.com/openknowledgebe/equalstreetnames-gent) | @jbelien |
| 🇧🇪 | Leuven | - | [equalstreetnames-leuven](https://github.com/openknowledgebe/equalstreetnames-leuven) | @jbelien |
| 🇷🇸 | Belgrade | https://naziviulica.openstreetmap.rs/ | [equalstreetnames-belgrade](https://github.com/stalker314314/equalstreetnames-belgrade) | @stalker314314 |

See [documentation](https://github.com/openknowledgebe/equalstreetnames/blob/master/docs/replicate.md) if you want to replicate the project in your city.

**Comment by jbelien** [comment]
Should we bundle all the versions in one single repository ?

**Comment by stalker314314** [comment]
You can see my changes here: https://github.com/stalker314314/equalstreetnames split into 3 different buckets (pipeline, web and data changes). They are not big, but also not easily abstracted away. I can understand how pipeline changes can be abstracted - have come config file that can define your overpass query and languages of interest.

For web, since I am not good with web, I have no idea how to pull that (but we need to abstract away languages, site needs to be localized, map need to have different bounding box) - some pre/post processing of html?

Data should not reside in git (or it could, but updating might be mess, maybe keep it out of git, or use it as submodule). Not sure if you would adopt approach where all data is updated at once, with same script, or each individual owner is owning data for their city and it is external to this repo? I prefer latter.

**Comment by jbelien** [comment]
> Data should not reside in git (or it could, but updating might be mess, maybe keep it out of git, or use it as submodule).

I never played with Git submodules but I think having a submodule by "region" (city, ...) could indeed be a good solution for this !
I'll try to move everything related to Brussels (in our case) to a submodule and see how it goes !

Stay tuned 🎉

**Comment by jbelien** [comment]
@stalker314314 I restructured the repository to isolate all the data/information related to Brussels in the `cities/brussels` folder.

The scripts and structure should now be independent from any city !
I still have to remove the [this line](https://github.com/openknowledgebe/equalstreetnames/blob/master/scripts/geojson.php#L370) to make the scripts completely independent of the city. I'll do that as soon as I have finished to update all the wikidata profiles.

The `cities/brussels` could become a sub-module !

Let me know if you think the new structure is good enough to include Belgrade as a sub-module too (I'll work on the loader - see #25 - this afternoon or tomorrow) !

**Comment by stalker314314** [comment]
Awesome. I will try it by merging Belgrade! But, what are next steps for me - should I create PR to add Belgrade here, or keep it in fork, or wait for submodules?

**Comment by jbelien** [comment]
> should I create PR to add Belgrade here, or keep it in fork, or wait for submodules?

Let's try to go for sub-modules. I'll move `brussels` to a sub-module !
Ping me when your sub-module (with a structure similar to the `cities/brussels` folder is ready 🎉

**Comment by jbelien** [comment]
Done ! Brussels is now a [sub-module](https://github.com/openknowledgebe/equalstreetnames-brussels) ! 🍾

**Comment by jbelien** [comment]
@stalker314314 Looking at your scripts, I just realized I still need to make the languages configurable in [`scripts/geojson.php`](https://github.com/openknowledgebe/equalstreetnames/blob/master/scripts/geojson.php). I'll take care of it tomorrow !

**Comment by stalker314314** [comment]
Hi,
There are still some artifacts:) They don't block me, just wanted to let you know:
https://github.com/openknowledgebe/equalstreetnames/blob/master/scripts/geojson.php#L104
https://github.com/openknowledgebe/equalstreetnames/blob/master/scripts/geojson.php#L151

and `getGender` could be improved: https://github.com/openknowledgebe/equalstreetnames/blob/master/scripts/geojson.php#L388

**Comment by stalker314314** [comment]
These one too:
https://github.com/openknowledgebe/equalstreetnames/blob/master/resources/map.ts#L17
https://github.com/openknowledgebe/equalstreetnames/blob/master/resources/map.ts#L34

(sorry if I am annoying you, I am just dumping all missing places as I go, and since I am first one, I guess this is expected. Hopefully, next city will not need to do all of this:D)

**Comment by jbelien** [comment]
Awesome ! Nice catch !
I'll fix that later today !
You're definitely not annoying me ! Thanks for your help !

**Comment by jbelien** [comment]
I updated the scripts !
And moved the map settings in `.env` (see step 5 of "[Run locally](https://github.com/openknowledgebe/equalstreetnames#run-locally)")
